### ISSUE TITLE
Python module pdb missing from SDK

### ISSUE THREAD

**Issue by n-west** [balister/oe-gnuradio-manifest#2]
I'll be leaving a couple of notes on building GR with a new SDK on a couple of machines.
```
$ repo info
Manifest branch: master
Manifest merge branch: daisy
Manifest groups: all,-notdefault
```

```
[ 12%] Generating python docstrings for pmt_swig_doc
Traceback (most recent call last):
  File "/opt/code/gnuradio/docs/doxygen/swig_doc.py", line 32, in <module>
    from doxyxml import DoxyIndex, DoxyClass, DoxyFriend, DoxyFunction, DoxyFile
  File "/opt/code/gnuradio/docs/doxygen/doxyxml/__init__.py", line 67, in <module>
    from doxyindex import DoxyIndex, DoxyFunction, DoxyParam, DoxyClass, DoxyFile, DoxyNamespace, DoxyGroup, DoxyFriend, DoxyOther
  File "/opt/code/gnuradio/docs/doxygen/doxyxml/doxyindex.py", line 29, in <module>
    from base import Base
  File "/opt/code/gnuradio/docs/doxygen/doxyxml/base.py", line 29, in <module>
    import pdb
ImportError: No module named pdb
make[2]: *** [gnuradio-runtime/swig/pmt_swig_doc.i] Error 1
make[1]: *** [gnuradio-runtime/swig/CMakeFiles/pmt_swig_swig_doc.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by balister** [comment]
hmm, missed this. ANy idea if it is still true?

**Comment by n-west** [comment]
Not sure, but I don't care anymore :-)
